version: '3.8'
services:
  postgres_database:
    container_name: postgres_database_tm
    image: postgres
    restart: always
    volumes:
      - pgData:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8001:5432"
    healthcheck:
      test: "exit 0"
    networks:
      - appNet
  pg_admin:
    container_name: pgadmin4_server_tm
    image: dpage/pgadmin4
    restart: always
    depends_on:
      postgres_database:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - appNet
    volumes:
      - pgData:/var/lib/postgresql
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - appNet
  app:
    container_name: task-manager
    build: ./task-manager/
    ports:
      - "8080:8080"
    networks:
      - appNet
    depends_on:
      - postgres_database
  ui_app:
    container_name: task-manager-ui
    build: ./task-manager-ui/
    ports:
      - "4200:4200"
    networks:
      - appNet
    depends_on:
      - postgres_database
networks:
  appNet:
volumes:
  pgData: